### ISSUE TITLE
High CPU usage on Gnome 3.32

### ISSUE THREAD

**Issue by salaros** [zhangkaizhao/gnome-shell-extension-tray-icons#2]
On Ubuntu Disco Dingo + Gnome 3.32 your extension spikes CPU usage to 30-40% on my 8th-gen Core i7 laptop (gnome-shell process), the usage decreases as soon as I disable your extension and restart the shell.
However I noticed the same bug on few other tray-related extensions

**Comment by zegkljan** [comment]
Can confirm exactly the same issue on Arch Linux.

**Comment by zhangkaizhao** [comment]
Hi! I am investigating on this issue.

It seems like the root cause is the remove of `Lang.Class`:
https://gitlab.gnome.org/GNOME/gnome-shell/commit/bacfdbbb0338b94295c64093523bca7ba8d5c5ca
via https://github.com/micheleg/dash-to-dock/issues/877#issuecomment-459659250
via https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/87

I just removed source code lines with this feature and the CPU usage was reduced to normal.
Will find out if there is another solution for this feature. Or will remove these lines.

Thanks for the report!

**Comment by zegkljan** [comment]
You might be interested in similar issue in Topicons redux: https://gitlab.com/pop-planet/TopIcons-Redux/issues/12

It also experiences high CPU load but strangely, opening the extension's settings from gnome tweaks gets rid of the CPU load. Opening it again makes the load come back. Opening it for the third time makes it go away again, etc.

**Comment by salaros** [comment]
@zhangkaizhao thanks for quick response. Will you release the changes you were talking about? Or at least provide them in a dev-branch?

**Comment by zhangkaizhao** [comment]
After some more testing, I don't think I have caught the root cause.
Sorry.

**Comment by zhangkaizhao** [comment]
@zegkljan Thanks. I will take a look.

**Comment by coxackie** [comment]
Many thanks for your work. I hope you can find a solution. This is the best of the gnome tray icon extensions, short and simple.

**Comment by treba123** [comment]
See also https://gitlab.gnome.org/GNOME/gnome-shell/issues/1054

**Comment by treba123** [comment]
This has been confirmed to be an upstream bug: https://gitlab.gnome.org/GNOME/gnome-shell/issues/1054#note_462698

**Comment by zhangkaizhao** [comment]
@treba123 Yeah. Let's wait for the fix from upstream.

**Comment by coxackie** [comment]
@zhangkaizhao Makes sense to wait. Meanwhile, would you consider also "modernizing" (replacing) the`Lang.Class` parts of the code in order to ensure there will not be future problems? A lot of people depend on this extension.

**Comment by zhangkaizhao** [comment]
@coxackie I am sorry but I made a mistake before. There is no `Lang.Class` in the source code. Instead there are some `Lang.bind`s there. I don't know if this belongs to `Lang.Class`. I am a novice. But we can convert them to ES6 arrow functions. And I think this is safe.

Arrow functions
https://developer.mozilla.org/docs/Web/JavaScript/Reference/Functions/Arrow_functions
https://hacks.mozilla.org/2015/06/es6-in-depth-arrow-functions/

Other references:
* https://ptomato.wordpress.com/2017/07/14/inventing-gobject-es6-classes/
* https://ptomato.wordpress.com/2017/04/28/gjs-whats-next/
  > The main language features that this will bring in are: classes (45) and ES7 async/await statements (52). At that point, the only major ES6 feature that we will still be missing is modules.
* https://stackoverflow.com/questions/52176326/should-i-use-es6-or-lang-classes-when-developing-gnome-shell-and-extensions
* https://gitlab.gnome.org/GNOME/gjs/wikis/Home

**Comment by coxackie** [comment]
This sounds good - if you create a dev branch with the changes I can test it. (And you can always submit for approval at GNOME extensions and get better feedback, although they have a huge backlog right now.)

**Comment by zhangkaizhao** [comment]
@coxackie OK. I just created a dev branch for test: [es6-arrow-functions](https://github.com/zhangkaizhao/gnome-shell-extension-tray-icons/tree/es6-arrow-functions).
Feel free to check it out and test.

**Comment by coxackie** [comment]
@zhangkaizhao This was quick... I am already testing - loads OK, will keep checking if there are any issues.

**Comment by zhangkaizhao** [comment]
Wow. I found a strange workaround for this issue.
Just switch enable/disable any GNOME Shell extension which draws anything in the top panel (left, center or right) e.g. Applications menu(at left), Openweather(at center), Argos(at right), etc. several times until the CPU usage falls to normal. This does not need too many times. The disadvantage is after the GNOME Shell session restarted the CPU usage is back to high and the workaround needs to apply again. :laughing:

**Comment by coxackie** [comment]
@zhangkaizhao   lol, this indeed works. What a mess...

**Comment by coxackie** [comment]
@zhangkaizhao I can confirm that es6-arrow-functions works similar to master - maybe also alter metadata to include 3.32, and submit for review?

**Comment by salaros** [comment]
any news on this topic?

**Comment by treba123** [comment]
@salaros: there's a [workaround](https://github.com/endlessm/gnome-shell/commit/11ddabfb22aedb3c35abe06d2cf0205f223cca03) which works, but the devs are still investigate the issue to solve it properly.

**Comment by ProfRon** [comment]
Just tried both branches ("e6-arrow-functions" and "ignore-recreating-tray-after-session-idle").
Neither helped.
That is, they both work at making the tray icons visible (so far so good) but the CPU remains very busy (one core at over 80%). 
This was observed using Wayland, Archlinux, Gnome 3.32, on a machine with 8 cores. 
I'm not 100% sure that I did everything right with "git clone" followed by "git checkout" and Gnome-Tweak for turning things off and on, etc., so I'll play with it a little more.  
Take it with a pinch of salt, in other words.

**Comment by treba123** [comment]
@ProfRon: it's a shell bug, nothing this extension could fix. So you'd need the workaround from my comment above applied to Gnome Shell. See https://gitlab.gnome.org/GNOME/gnome-shell/issues/1054 for more details.

**Comment by treba123** [comment]
Fixed upstream, should come to 3.32.2 (https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/521)

**Comment by coxackie** [comment]
Great @treba123 many thanks for debugging this, and coming to a solution.
@zhangkaizhao would it be able now to submit the the changes you have made to Gnome extensions for review, so we do not have to install through git the latest?

**Comment by zhangkaizhao** [comment]
I think this issue can be closed now.
