### ISSUE TITLE
Extremly big icons

### ISSUE THREAD

**Issue by ogarcia** [zhangkaizhao/gnome-shell-extension-tray-icons#4]
On latest GNOME 3.32.2 I see some icons (like pidgin one) extremly big.

A screenshot:
![trayicons](https://user-images.githubusercontent.com/572924/57833762-15cf2f00-77bb-11e9-9ef6-7d1bf1027ebd.png)

**Comment by zhangkaizhao** [comment]
Hi @ogarcia . Please update this extension from [GNOME extensions website](https://extensions.gnome.org/) and try again. This issue should be fixed.

**Comment by zhangkaizhao** [comment]
I am closing this issue. Please feel free to reopen it if you still run into it.
